# Generated by Django 4.2 on 2023-07-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueAnsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='jobtitle',
        ),
        migrations.AlterField(
            model_name='post',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
