# Generated by Django 4.2 on 2023-07-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueAnsapp', '0002_remove_post_jobtitle_alter_post_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
